INSERT INTO `product` (
    product_id, product_name, stock_quantity, description, short_desc, 
    unit_price, product_point, sold_number, category_code
) VALUES

(1,  'Claw Hammer 23mm',                              150, 'Professional claw hammer with fiberglass handle', 'Claw Hammer 23mm',                               45.90,  46, 0, 4),
(2,  'Cross Pein Pin Hammer 14mm',                     200, 'Lightweight precision pin hammer',                'Cross Pein Pin Hammer 14mm',                     32.50,  33, 0, 4),
(3,  'Cross Pein Pin Hammer 18mm',                     180, 'Medium cross pein hammer for general work',       'Cross Pein Pin Hammer 18mm',                     38.90,  39, 0, 4),
(4,  'Magnetic Claw Hammer',                           120, 'Claw hammer with magnetic nail starter',          'Magnetic Claw Hammer',                           59.90,  60, 0, 4),
(5,  'Short-Handle Mini Hammer (16 cm)',               300, 'Compact hammer for tight spaces',                 'Short-Handle Mini Hammer',                       19.90,  20, 0, 4),
(6,  'CHISEL SET MGZ-3PC',                              80, '3-piece professional woodworking chisel set',     '3-Piece Woodworking Chisel Set',                 89.90,  90, 0, 4),
(7,  'Hammer with Rubber Grip',                        140, 'Ergonomic rubber grip hammer',                    'Hammer with Rubber Grip',                        49.90,  50, 0, 4),
(8,  'Precision Screwdriver Set',                      200, '32-in-1 magnetic precision screwdriver kit',      'Precision Screwdriver Set',                      69.90,  70, 0, 4),
(9,  'INCGO Removeable Screwdriver 2in1 (19cm)',        250, 'Reversible flat & Phillips screwdriver',          'INCGO 2in1 Screwdriver',                         24.90,  25, 0, 4),
(10, 'EMTOP Cordless Screwdriver ECSR0403',             60, '4V rechargeable cordless screwdriver with LED',   'EMTOP Cordless Screwdriver',                    149.90, 150, 0, 5),
(11, 'TACTIX Insulated Screwdriver Set (6 pieces)',     90, 'VDE 1000V certified insulated screwdrivers',      'TACTIX Insulated Screwdriver Set',               99.90, 100, 0, 4),
(12, 'Knife with Cutter Blade Set',                    300, 'Heavy-duty utility knife + 10 spare blades',      'Knife with Cutter Blade Set',                    29.90,  30, 0, 4),
(13, 'Heavy Duty Batik Protective Hand Gloves (12 Pairs)',100,'Industrial cotton gloves – bulk 12 pairs',         'Protective Hand Gloves 12 Pairs',                79.90,  80, 0, 4),
(14, 'Multi-Use Foldable PVC Hand Truck Trolley (300kg)',40,'Portable folding trolley 300kg capacity',         'Foldable Hand Truck 300kg',                     199.90, 200, 0, 1),
(15, '31-Piece T-handle Wrench/Screwdriver Set',        70, 'Complete T-handle hex & Torx tool set',           '31-Piece T-handle Set',                         179.90, 180, 0, 4),
(16, '32-in-1 Magnetic Electron Screwdriver Set',      180, 'Magnetic precision screwdriver kit with extension','32-in-1 Magnetic Screwdriver',                  89.90,  90, 0, 4),
(17, 'Plastic Storage Drawer Rack Desk Organizer 3 Tier',150,'3-tier plastic desk drawer organizer',            '3-Tier Desk Organizer',                          49.90,  50, 0, 1),
(18, 'Wall-Mounted Tissue Box-Cyan',                    200, 'Waterproof wall-mounted tissue holder (cyan)',    'Wall-Mounted Tissue Box Cyan',                   39.90,  40, 0, 1),
(19, 'Wall-Mounted Stainless-Steel 2-Layer Bathroom Rack',80,'Rust-proof 2-tier stainless steel bathroom shelf','Stainless Steel Bathroom Rack',                 129.90, 130, 0, 1),
(20, 'CHANYI 3 Tier Plastic Document File Tray',       120, 'Stackable A4 document tray organizer',            'CHANYI 3-Tier File Tray',                        59.90,  60, 0, 2),
(21, '3-Tier Heavy-Duty Workshop Trolley Rack',         30, 'Mobile 3-tier tool trolley with wheels',          '3-Tier Workshop Trolley',                       289.90, 290, 0, 1),
(22, '3 Shelf Multipurpose Rectangular Rack',           60, 'Sturdy rectangular storage shelf',                '3-Shelf Rectangular Rack',                      139.90, 140, 0, 1),
(23, 'Car Universal Phone Holder',                      250, '360° dashboard/windshield phone mount',           'Car Universal Phone Holder',                     39.90,  40, 0, 3),
(24, 'HOTAK Driver Click Extendable Ratchet 3/8"',      90, 'Professional extendable ratchet wrench 37cm',     'HOTAK Extendable Ratchet',                      159.90, 160, 0, 4),
(25, 'Microfiber Wash Mitt Cleaning Gloves (1pc)',      400, 'Ultra-soft scratch-free car washing glove',       'Microfiber Wash Mitt',                           19.90,  20, 0, 3),
(26, 'Car Dashboard Anti-Slip Mat (30x15cm)',           500, 'Non-slip mat for phone & accessories',            'Anti-Slip Dashboard Mat',                        15.90,  16, 0, 3),
(27, 'WAXCO Auto Silicon Car Lubricant Spray (300ml)',  300, 'Silicon lubricant & protector spray',             'WAXCO Silicon Spray 300ml',                      29.90,  30, 0, 3),
(28, 'ROLLINGDOG Heavy Duty Scissors (216mm)',          180, 'Titanium-coated ultra-sharp scissors',            'ROLLINGDOG Heavy Duty Scissors',                 49.90,  50, 0, 4),
(29, 'EMTOP Auto Air Compressor (35L/min)',             50, '12V portable tire inflator with LED & gauge',     'EMTOP Car Air Compressor',                      249.90, 250, 0, 5),
(30, 'Stainless Steel Scissor',                         400, 'General-purpose rust-resistant scissors',         'Stainless Steel Scissor',                        12.90,  13, 0, 2),
(31, 'TACTIX Color Quick Change Driver Bit Set (32 pcs)',150,'Color-coded magnetic bit set with holder',         'TACTIX 32-Pc Bit Set',                           79.90,  80, 0, 4),
(32, 'TACTIX 39-Drawers Storage Bin',                   40, 'Professional parts organizer 39 drawers',         'TACTIX 39-Drawer Storage Bin',                  199.90, 200, 0, 1),
(33, 'Socket Tool Set (46 pieces)',                     60, 'Complete 1/4" & 3/8" drive socket set',           '46-Piece Socket Set',                           289.90, 290, 0, 4),
(34, '2 Drawers Storage Box (32cm)',                    200, 'Stackable clear plastic drawer organizer',        '2-Drawer Storage Box',                           39.90,  40, 0, 1),
(35, 'Durable Bamboo Wooden Tissue Box (25x12cm)',      180, 'Eco-friendly natural bamboo tissue holder',       'Bamboo Wooden Tissue Box',                       49.90,  50, 0, 1),
(36, 'COMIX Marker Pen Black (12 Pcs)',                 300, 'Permanent marker 0.5-1.5mm – pack of 12',         'COMIX Black Marker 12-Pack',                     29.90,  30, 0, 2),
(37, 'COMIX A5 Business Notebook (122 sheets)',         250, 'Premium hard-cover lined A5 notebook',            'COMIX A5 Notebook',                              24.90,  25, 0, 2),
(38, '2B Mechanical Pencil & Lead Set',                 500, '0.5mm mechanical pencil with extra leads',        '2B Mechanical Pencil Set',                       12.90,  13, 0, 2),
(39, 'Sticky Notes',                                    400, 'Assorted color sticky notes – 6 pads',            'Sticky Notes 6-Pack',                            19.90,  20, 0, 2);